### ISSUE TITLE
hacker found !! important

### ISSUE THREAD

**Issue by aleks00250** [ArmaMC/Arma-MC#8]
hey on the server im aleks00250 and im tired of BASICTY hacking by putting me in traps and destroying the whole spawn I don't have a picture but I would like to see if u can try to stop him its getting annoying for me

**Comment by aleks00250** [comment]
and he also was threatning me and another person he was gonna hack us too

**Comment by ArmaMC** [comment]
Server is not owned/operated by the Arma-MC development team any player/staff/server related issues need to be posted on the Evolvecraft forum, thank you
- xch0w

Link to said forum: http://evolvecraft.com/cpforum
